//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace andengine.net.examples
{
	
	
	public partial class Resource
	{
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int new_in_version_changes = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int new_in_version_versioncode = 2131034112;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int btn_get_involved = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int tv_listrow_example_name = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int tv_listrow_examplegroup_name = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int xmllayoutexample_rendersurfaceview = 2131099651;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_examples = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int listrow_example = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int listrow_examplegroup = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int xmllayoutexample = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int btn_get_involved_caption = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int dialog_benchmark_submit_message = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int dialog_benchmark_submit_title = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int dialog_benchmarks_submit_please_message = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int dialog_benchmarks_submit_please_title = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int dialog_first_app_launch_message = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int dialog_first_app_launch_title = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int dialog_modplayerexample_loading_to_external_message = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int dialog_modplayerexample_loading_to_external_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int dialog_new_in_this_version_title = 2130968582;
			
			// aapt resource value: 0x7f04001b
			public const int example_analogonscreencontrol = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int example_analogonscreencontrols = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int example_animatedsprites = 2130968605;
			
			// aapt resource value: 0x7f04005f
			public const int example_app_cityradar = 2130968671;
			
			// aapt resource value: 0x7f04001e
			public const int example_augmentedreality = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int example_augmentedrealityhorizon = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int example_autoparallaxbackground = 2130968608;
			
			// aapt resource value: 0x7f040056
			public const int example_benchmark_animation = 2130968662;
			
			// aapt resource value: 0x7f040059
			public const int example_benchmark_entitymodifier = 2130968665;
			
			// aapt resource value: 0x7f040057
			public const int example_benchmark_particlesystem = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int example_benchmark_physics = 2130968664;
			
			// aapt resource value: 0x7f04005a
			public const int example_benchmark_sprite = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int example_benchmark_tickertext = 2130968667;
			
			// aapt resource value: 0x7f040021
			public const int example_boundcamera = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int example_changeabletext = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int example_collisiondetection = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int example_colorkeytexturesourcedecorator = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int example_coordinateconversion = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int example_customfont = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int example_digitalonscreencontrol = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int example_easefunction = 2130968616;
			
			// aapt resource value: 0x7f040043
			public const int example_entitymodifier = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int example_entitymodifierirregular = 2130968644;
			
			// aapt resource value: 0x7f04005c
			public const int example_game_pong = 2130968668;
			
			// aapt resource value: 0x7f04005e
			public const int example_game_racer = 2130968670;
			
			// aapt resource value: 0x7f04005d
			public const int example_game_snake = 2130968669;
			
			// aapt resource value: 0x7f040029
			public const int example_imageformats = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int example_levelloader = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int example_line = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int example_loadtexture = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int example_menu = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int example_modplayer = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int example_movingball = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int example_multiplayer = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int example_multitouch = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int example_music = 2130968626;
			
			// aapt resource value: 0x7f040035
			public const int example_particlesystemcool = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int example_particlesystemnexus = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int example_particlesystemsimple = 2130968631;
			
			// aapt resource value: 0x7f040034
			public const int example_pathmodifier = 2130968628;
			
			// aapt resource value: 0x7f040033
			public const int example_pause = 2130968627;
			
			// aapt resource value: 0x7f040039
			public const int example_physics = 2130968633;
			
			// aapt resource value: 0x7f040038
			public const int example_physicscollisionfiltering = 2130968632;
			
			// aapt resource value: 0x7f04003a
			public const int example_physicsfixedstep = 2130968634;
			
			// aapt resource value: 0x7f04003d
			public const int example_physicsjump = 2130968637;
			
			// aapt resource value: 0x7f04003b
			public const int example_physicsmousejoint = 2130968635;
			
			// aapt resource value: 0x7f04003e
			public const int example_physicsremove = 2130968638;
			
			// aapt resource value: 0x7f04003c
			public const int example_physicsrevolutejoint = 2130968636;
			
			// aapt resource value: 0x7f04003f
			public const int example_pinchzoom = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int example_rectangle = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int example_repeatingspritebackground = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int example_rotation3d = 2130968642;
			
			// aapt resource value: 0x7f040045
			public const int example_screencapture = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int example_sound = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int example_splitscreen = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int example_sprite = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int example_spriteremove = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int example_strokefont = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int example_submenu = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int example_text = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int example_textmenu = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int example_textureoptions = 2130968654;
			
			// aapt resource value: 0x7f040050
			public const int example_tickertext = 2130968656;
			
			// aapt resource value: 0x7f04004f
			public const int example_tmxtiledmap = 2130968655;
			
			// aapt resource value: 0x7f040051
			public const int example_touchdrag = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int example_unloadresources = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int example_updatetexture = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int example_xmllayout = 2130968660;
			
			// aapt resource value: 0x7f040055
			public const int example_zoom = 2130968661;
			
			// aapt resource value: 0x7f040015
			public const int examplegroup_advanced = 2130968597;
			
			// aapt resource value: 0x7f040018
			public const int examplegroup_app = 2130968600;
			
			// aapt resource value: 0x7f040014
			public const int examplegroup_audio = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int examplegroup_background = 2130968598;
			
			// aapt resource value: 0x7f04001a
			public const int examplegroup_benchmark = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int examplegroup_game = 2130968601;
			
			// aapt resource value: 0x7f04000e
			public const int examplegroup_modifier_and_animation = 2130968590;
			
			// aapt resource value: 0x7f040011
			public const int examplegroup_multiplayer = 2130968593;
			
			// aapt resource value: 0x7f040017
			public const int examplegroup_other = 2130968599;
			
			// aapt resource value: 0x7f040010
			public const int examplegroup_particlesystems = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int examplegroup_physics = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int examplegroup_simple = 2130968589;
			
			// aapt resource value: 0x7f040013
			public const int examplegroup_text = 2130968595;
			
			// aapt resource value: 0x7f04000f
			public const int examplegroup_touch = 2130968591;
			
			// aapt resource value: 0x7f040000
			public const int tv_xmllayoutexample_above = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int tv_xmllayoutexample_below = 2130968577;
			
			private String()
			{
			}
		}
	}
}
